services:
  app:
    build: ../memes/public
    ports:
      - "${PUBLIC_PORT}:8000"
    volumes:
      - ../memes/public/src:/opt/app
    environment:
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_DB_NAME: ${DB_DB_NAME:?}
      DB_PORT: ${DB_PORT:?}
      DB_HOST: ${DB_HOST:?}
      C3_UPLOAD_URL: ${C3_UPLOAD_URL:?}
      APP_NAME: ${APP_NAME:?}
      APP_VERSION: ${APP_VERSION:?}
      APP_DEBUG: ${APP_DEBUG:?}
    networks:
      - backend

  gateway:
    build: ../memes/gateway
    expose:
      - "8000"
    volumes:
      - ../memes/gateway/src:/opt/app
    environment:
      C3_URL: ${C3_URL:?}
      C3_ACCESS_KEY: ${C3_ACCESS_KEY:?}
      C3_SECRET_KEY: ${C3_SECRET_KEY:?}
      C3_BUCKET_NAME: ${C3_BUCKET_NAME:?}
      APP_NAME: ${APP_NAME:?}
      APP_VERSION: ${APP_VERSION:?}
      APP_DEBUG: ${APP_DEBUG:?}
    networks:
      - backend

networks:
  backend:
    driver: bridge